name: Build Prod

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Node.js 12.18.1
        uses: actions/setup-node@v3
        with:
          node-version: 12.18.1
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Commit lib
        shell: sh
        run: |
          git config --global user.name "Noci"
          git config --global user.email "noci-io@users.noreply.github.com"
          git add lib
          npm config set commit-hooks false
          npm config set git-tag-version false
          npm version patch
          git commit -am "Build library"
          git push
